// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq0aDFCFb6HErfnyq4iaX2OeNUVIZ2m5g',
    appId: '1:415217552470:web:85ac421c811eb1bd3fbff7',
    messagingSenderId: '415217552470',
    projectId: 'smartfloodsys',
    authDomain: 'smartfloodsys.firebaseapp.com',
    storageBucket: 'smartfloodsys.firebasestorage.app',
    measurementId: 'G-22RGB8S2ZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSNURFASdwg7UDAbQza0omCKMvzBP3Kz8',
    appId: '1:415217552470:android:31e74c35476bdf343fbff7',
    messagingSenderId: '415217552470',
    projectId: 'smartfloodsys',
    storageBucket: 'smartfloodsys.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeVHXS5rghMfGB-QZkUse3VQPWE5q0mPw',
    appId: '1:415217552470:ios:0381a121f8577cf33fbff7',
    messagingSenderId: '415217552470',
    projectId: 'smartfloodsys',
    storageBucket: 'smartfloodsys.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeVHXS5rghMfGB-QZkUse3VQPWE5q0mPw',
    appId: '1:415217552470:ios:0381a121f8577cf33fbff7',
    messagingSenderId: '415217552470',
    projectId: 'smartfloodsys',
    storageBucket: 'smartfloodsys.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCq0aDFCFb6HErfnyq4iaX2OeNUVIZ2m5g',
    appId: '1:415217552470:web:67017c0f3bd02c013fbff7',
    messagingSenderId: '415217552470',
    projectId: 'smartfloodsys',
    authDomain: 'smartfloodsys.firebaseapp.com',
    storageBucket: 'smartfloodsys.firebasestorage.app',
    measurementId: 'G-8JCMDXWR5Y',
  );
}
